#!/usr/bin/env node
'use strict';

/*
Cleans up Feather CSS assets for use on twitter.github.io. Run this whenever
installing new versions of Feather.
*/

const fs = require('fs');
const path = require('path');

const ROOT_PATH = path.join(__dirname, '..');
const FEATHER_CSS_PATHS = [
  path.join(ROOT_PATH, 'css/feather-component-button.css'),
  path.join(ROOT_PATH, 'css/feather-component-grid.css'),
  path.join(ROOT_PATH, 'css/feather-core.css')
];

function addLegalLines() {
  const copyrightYear = new Date().getFullYear();
  const encoding = 'utf-8';
  const legalLine = `/*! Copyright ${copyrightYear} Twitter Inc. All rights reserved. */`;

  FEATHER_CSS_PATHS.forEach(filePath => {
    const oldCode = fs.readFileSync(filePath, { encoding });

    if (oldCode.startsWith(legalLine)) { return; }

    const newCode = `${legalLine}\n\n${oldCode}`;
    fs.writeFileSync(filePath, newCode, { encoding });
  });
}

addLegalLines();
